"""Generate only contract metadata; transport and ergonomic methods are handwritten."""
import argparse
import hashlib
import json
from pathlib import Path


def render(root):
    raw = (root / "api/gen/openapi.bundle.json").read_bytes()
    spec = json.loads(raw)
    routes = sorted((method.upper(), path) for path, entry in spec["paths"].items()
                    for method in entry if method in {"get", "post", "put", "patch", "delete", "head"})
    return ("# Generated by sdk/python/generate.py. DO NOT EDIT.\n"
            "API_VERSION = 'v1'\n"
            f"CONTRACT_SHA256 = {hashlib.sha256(raw).hexdigest()!r}\n"
            f"ROUTES = {tuple(routes)!r}\n")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    root = Path(__file__).resolve().parents[2]
    target = Path(__file__).parent / "lantai/_contract.py"
    expected = render(root)
    if args.check:
        if not target.exists() or target.read_text() != expected:
            p.exit(1, "Python contract metadata drift; run python3 sdk/python/generate.py\n")
    else:
        target.write_text(expected)
