// Code generated by scripts/gen/errcodes from schemas/common/v1/error-codes.json. DO NOT EDIT.

package errcode

// 已登记的错误码。
const (
	// AssetCheckedOut 资产被其他有效执行轮次签出
	AssetCheckedOut Code = "ASSET_CHECKED_OUT"
	// AssetInTrash 资产或版本在回收站中
	AssetInTrash Code = "ASSET_IN_TRASH"
	// AssetInUse 对象在用（已发布、被引用、正在修改或有流程），不能删除
	AssetInUse Code = "ASSET_IN_USE"
	// AssetLocked 资产或祖先路径已锁定，需要人解锁
	AssetLocked Code = "ASSET_LOCKED"
	// AssetPurged 对象已清除，只剩墓碑（仅对有权查看墓碑者返回）
	AssetPurged Code = "ASSET_PURGED"
	// AuthRequired 缺少有效认证；重新认证，不自动升权
	AuthRequired Code = "AUTH_REQUIRED"
	// BaseVersionConflict 声明的基线版本已落后
	BaseVersionConflict Code = "BASE_VERSION_CONFLICT"
	// BlobGrantRequired 内容需要本操作的上传或授权证明；不区分内容是否已存在
	BlobGrantRequired Code = "BLOB_GRANT_REQUIRED"
	// BudgetExhausted 预算已耗尽；执行暂停，需要预算变更
	BudgetExhausted Code = "BUDGET_EXHAUSTED"
	// ChecksNotSatisfied 验收要求的检查或证据未满足
	ChecksNotSatisfied Code = "CHECKS_NOT_SATISFIED"
	// CursorExpired 事件游标超出保留期；先固定起点水位再全量重同步
	CursorExpired Code = "CURSOR_EXPIRED"
	// DependencyCycle 声明的依赖关系形成环
	DependencyCycle Code = "DEPENDENCY_CYCLE"
	// ExtensionActivationStale 扩展激活代次、包摘要或启用状态已不是当前值
	ExtensionActivationStale Code = "EXTENSION_ACTIVATION_STALE"
	// ExtensionPointUnsupported 扩展点、target 或能力在当前阶段不受支持；不静默忽略配置
	ExtensionPointUnsupported Code = "EXTENSION_POINT_UNSUPPORTED"
	// FieldRequiresSpecialCommand 安全相关字段只能通过专门命令修改
	FieldRequiresSpecialCommand Code = "FIELD_REQUIRES_SPECIAL_COMMAND"
	// FlowRequired 该动作需要有效任务或流程上下文
	FlowRequired Code = "FLOW_REQUIRED"
	// Forbidden 当前身份、角色或策略不允许该动作
	Forbidden Code = "FORBIDDEN"
	// HashMismatch 内容与声明的哈希或大小不符
	HashMismatch Code = "HASH_MISMATCH"
	// HumanGrantMismatch 人类授权与动作、目标集合、请求摘要或 operation 不一致
	HumanGrantMismatch Code = "HUMAN_GRANT_MISMATCH"
	// HumanProofRequired 敏感动作需要绑定目标的有效人类授权（HumanGrant）
	HumanProofRequired Code = "HUMAN_PROOF_REQUIRED"
	// IdempotencyConflict 同一幂等键对应不同请求摘要；新意图必须使用新键
	IdempotencyConflict Code = "IDEMPOTENCY_CONFLICT"
	// IdempotencyResultExpired 已知旧操作超过响应缓存期；按返回的对象或操作摘要读取当前状态
	IdempotencyResultExpired Code = "IDEMPOTENCY_RESULT_EXPIRED"
	// Internal 服务端内部错误；先查询 operation，再按其结果决定，不盲重启外部副作用
	Internal Code = "INTERNAL"
	// InvalidStateTransition 对象当前状态不允许该动作
	InvalidStateTransition Code = "INVALID_STATE_TRANSITION"
	// LeaseStale 执行轮次、fence、租约到期或 recovery_epoch 不再有效
	LeaseStale Code = "LEASE_STALE"
	// MaintenanceMode 实例处于维护、迁移或恢复状态，暂不接受该请求
	MaintenanceMode Code = "MAINTENANCE_MODE"
	// NotDue 回收站条目尚未到期
	NotDue Code = "NOT_DUE"
	// NotFound 对象不存在或调用者无权知道其存在
	NotFound Code = "NOT_FOUND"
	// NotPublishable 版本未审定通过、已停用或处于不可发布状态
	NotPublishable Code = "NOT_PUBLISHABLE"
	// NotPublished 资产没有有效发布版本（未发布或已暂停）
	NotPublished Code = "NOT_PUBLISHED"
	// NotSubmittable 版本当前状态不能提交审定
	NotSubmittable Code = "NOT_SUBMITTABLE"
	// OperationNeedsReconciliation 现有证据无法判定操作结果；禁止盲目重做
	OperationNeedsReconciliation Code = "OPERATION_NEEDS_RECONCILIATION"
	// PathConflict 路径已被占用或规范化后同名；不静默改名
	PathConflict Code = "PATH_CONFLICT"
	// PreconditionFailed 预期修订或 ETag 已过期
	PreconditionFailed Code = "PRECONDITION_FAILED"
	// PreconditionRequired 缺少必需的预期修订、ETag 或基线
	PreconditionRequired Code = "PRECONDITION_REQUIRED"
	// PublicationConflict 发布指针修订与预期不符
	PublicationConflict Code = "PUBLICATION_CONFLICT"
	// QuotaExceeded 超出配额；停止并报告
	QuotaExceeded Code = "QUOTA_EXCEEDED"
	// RateLimited 请求过快；按 retry_after_ms 等待
	RateLimited Code = "RATE_LIMITED"
	// RefAmbiguous 路径曾被复用，需指定 alias_generation 或永久 ID
	RefAmbiguous Code = "REF_AMBIGUOUS"
	// RefMismatch 版本不属于所给资产
	RefMismatch Code = "REF_MISMATCH"
	// ResourceBusy 资源有进行中的持久操作；按返回的 operation_id 查询
	ResourceBusy Code = "RESOURCE_BUSY"
	// ResultNotReady 结果尚未封存；稍后查询
	ResultNotReady Code = "RESULT_NOT_READY"
	// ResumeUnsupported 后端未声明所请求的恢复类型
	ResumeUnsupported Code = "RESUME_UNSUPPORTED"
	// ReviewTargetStale 审定目标已失效（新版提交、撤回或清单变化）
	ReviewTargetStale Code = "REVIEW_TARGET_STALE"
	// RightsPending 限制尚未完成核验；按 retry_after_ms 再查，不默认放行
	RightsPending Code = "RIGHTS_PENDING"
	// SchemaInvalid 请求或文档不符合 schema；按 details 逐条修正
	SchemaInvalid Code = "SCHEMA_INVALID"
	// SelfReviewForbidden 制作者不能审定或质检自己的产物
	SelfReviewForbidden Code = "SELF_REVIEW_FORBIDDEN"
	// SideEffectUnknown 外部副作用结果不明；先对账，禁止换键重试
	SideEffectUnknown Code = "SIDE_EFFECT_UNKNOWN"
	// StartKeyConflict 同一 execution_key 对应不同启动请求摘要
	StartKeyConflict Code = "START_KEY_CONFLICT"
	// StorageFull 存储空间不足；需人释放空间，之后可用同一幂等键重试
	StorageFull Code = "STORAGE_FULL"
	// StorageUnavailable 存储暂不可写或文件被占用；未确认的提交不会被报告成功
	StorageUnavailable Code = "STORAGE_UNAVAILABLE"
	// TaskAlreadyClaimed 席位已被其他会话领取
	TaskAlreadyClaimed Code = "TASK_ALREADY_CLAIMED"
	// TokenExpired 会话或令牌已过期
	TokenExpired Code = "TOKEN_EXPIRED"
	// TokenRevoked 会话或令牌已吊销，或属于旧 auth_epoch/recovery_epoch
	TokenRevoked Code = "TOKEN_REVOKED"
	// TOTPReplay 该动态码时间步已被使用；等待下一个验证码后重新输入
	TOTPReplay Code = "TOTP_REPLAY"
	// TrashHeld 回收站条目处于暂停清除状态
	TrashHeld Code = "TRASH_HELD"
	// UnsupportedCapability 执行后端或宿主未声明任务要求的能力；不派发
	UnsupportedCapability Code = "UNSUPPORTED_CAPABILITY"
	// UseRestricted 当前许可或来源限制禁止该用途
	UseRestricted Code = "USE_RESTRICTED"
)

var specs = []Spec{
	{Code: AssetCheckedOut, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "tasks", Summary: "资产被其他有效执行轮次签出"},
	{Code: AssetInTrash, HTTPStatus: 410, Retryable: false, Recovery: ActionHumanAction, Owner: "ledger", Summary: "资产或版本在回收站中"},
	{Code: AssetInUse, HTTPStatus: 409, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "对象在用（已发布、被引用、正在修改或有流程），不能删除"},
	{Code: AssetLocked, HTTPStatus: 409, Retryable: false, Recovery: ActionHumanAction, Owner: "ledger", Summary: "资产或祖先路径已锁定，需要人解锁"},
	{Code: AssetPurged, HTTPStatus: 410, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "对象已清除，只剩墓碑（仅对有权查看墓碑者返回）"},
	{Code: AuthRequired, HTTPStatus: 401, Retryable: false, Recovery: ActionReauthenticate, Owner: "identity", Summary: "缺少有效认证；重新认证，不自动升权"},
	{Code: BaseVersionConflict, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "ledger", Summary: "声明的基线版本已落后"},
	{Code: BlobGrantRequired, HTTPStatus: 403, Retryable: false, Recovery: ActionUploadContent, Owner: "storage", Summary: "内容需要本操作的上传或授权证明；不区分内容是否已存在"},
	{Code: BudgetExhausted, HTTPStatus: 409, Retryable: false, Recovery: ActionHumanAction, Owner: "agent_execution", Summary: "预算已耗尽；执行暂停，需要预算变更"},
	{Code: ChecksNotSatisfied, HTTPStatus: 422, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "验收要求的检查或证据未满足"},
	{Code: CursorExpired, HTTPStatus: 410, Retryable: false, Recovery: ActionResync, Owner: "events", Summary: "事件游标超出保留期；先固定起点水位再全量重同步"},
	{Code: DependencyCycle, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "provenance", Summary: "声明的依赖关系形成环"},
	{Code: ExtensionActivationStale, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "extensions", Summary: "扩展激活代次、包摘要或启用状态已不是当前值"},
	{Code: ExtensionPointUnsupported, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "extensions", Summary: "扩展点、target 或能力在当前阶段不受支持；不静默忽略配置"},
	{Code: FieldRequiresSpecialCommand, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "catalog", Summary: "安全相关字段只能通过专门命令修改"},
	{Code: FlowRequired, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "workflow", Summary: "该动作需要有效任务或流程上下文"},
	{Code: Forbidden, HTTPStatus: 403, Retryable: false, Recovery: ActionNone, Owner: "identity", Summary: "当前身份、角色或策略不允许该动作"},
	{Code: HashMismatch, HTTPStatus: 422, Retryable: false, Recovery: ActionUploadContent, Owner: "storage", Summary: "内容与声明的哈希或大小不符"},
	{Code: HumanGrantMismatch, HTTPStatus: 403, Retryable: false, Recovery: ActionHumanAction, Owner: "identity", Summary: "人类授权与动作、目标集合、请求摘要或 operation 不一致"},
	{Code: HumanProofRequired, HTTPStatus: 403, Retryable: false, Recovery: ActionHumanAction, Owner: "identity", Summary: "敏感动作需要绑定目标的有效人类授权（HumanGrant）"},
	{Code: IdempotencyConflict, HTTPStatus: 409, Retryable: false, Recovery: ActionFixRequest, Owner: "common", Summary: "同一幂等键对应不同请求摘要；新意图必须使用新键"},
	{Code: IdempotencyResultExpired, HTTPStatus: 410, Retryable: false, Recovery: ActionRefreshState, Owner: "common", Summary: "已知旧操作超过响应缓存期；按返回的对象或操作摘要读取当前状态"},
	{Code: Internal, HTTPStatus: 500, Retryable: false, Recovery: ActionPollOperation, Owner: "common", Summary: "服务端内部错误；先查询 operation，再按其结果决定，不盲重启外部副作用"},
	{Code: InvalidStateTransition, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "common", Summary: "对象当前状态不允许该动作"},
	{Code: LeaseStale, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "tasks", Summary: "执行轮次、fence、租约到期或 recovery_epoch 不再有效"},
	{Code: MaintenanceMode, HTTPStatus: 503, Retryable: true, Recovery: ActionRetry, Owner: "operations", Summary: "实例处于维护、迁移或恢复状态，暂不接受该请求"},
	{Code: NotDue, HTTPStatus: 409, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "回收站条目尚未到期"},
	{Code: NotFound, HTTPStatus: 404, Retryable: false, Recovery: ActionNone, Owner: "common", Summary: "对象不存在或调用者无权知道其存在"},
	{Code: NotPublishable, HTTPStatus: 409, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "版本未审定通过、已停用或处于不可发布状态"},
	{Code: NotPublished, HTTPStatus: 409, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "资产没有有效发布版本（未发布或已暂停）"},
	{Code: NotSubmittable, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "ledger", Summary: "版本当前状态不能提交审定"},
	{Code: OperationNeedsReconciliation, HTTPStatus: 409, Retryable: false, Recovery: ActionReconcile, Owner: "common", Summary: "现有证据无法判定操作结果；禁止盲目重做"},
	{Code: PathConflict, HTTPStatus: 409, Retryable: false, Recovery: ActionFixRequest, Owner: "catalog", Summary: "路径已被占用或规范化后同名；不静默改名"},
	{Code: PreconditionFailed, HTTPStatus: 412, Retryable: false, Recovery: ActionRefreshState, Owner: "common", Summary: "预期修订或 ETag 已过期"},
	{Code: PreconditionRequired, HTTPStatus: 428, Retryable: false, Recovery: ActionFixRequest, Owner: "common", Summary: "缺少必需的预期修订、ETag 或基线"},
	{Code: PublicationConflict, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "ledger", Summary: "发布指针修订与预期不符"},
	{Code: QuotaExceeded, HTTPStatus: 429, Retryable: false, Recovery: ActionNone, Owner: "common", Summary: "超出配额；停止并报告"},
	{Code: RateLimited, HTTPStatus: 429, Retryable: true, Recovery: ActionRetry, Owner: "common", Summary: "请求过快；按 retry_after_ms 等待"},
	{Code: RefAmbiguous, HTTPStatus: 409, Retryable: false, Recovery: ActionFixRequest, Owner: "catalog", Summary: "路径曾被复用，需指定 alias_generation 或永久 ID"},
	{Code: RefMismatch, HTTPStatus: 409, Retryable: false, Recovery: ActionFixRequest, Owner: "catalog", Summary: "版本不属于所给资产"},
	{Code: ResourceBusy, HTTPStatus: 423, Retryable: true, Recovery: ActionPollOperation, Owner: "common", Summary: "资源有进行中的持久操作；按返回的 operation_id 查询"},
	{Code: ResultNotReady, HTTPStatus: 409, Retryable: true, Recovery: ActionPollOperation, Owner: "agent_execution", Summary: "结果尚未封存；稍后查询"},
	{Code: ResumeUnsupported, HTTPStatus: 409, Retryable: false, Recovery: ActionNone, Owner: "agent_execution", Summary: "后端未声明所请求的恢复类型"},
	{Code: ReviewTargetStale, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "ledger", Summary: "审定目标已失效（新版提交、撤回或清单变化）"},
	{Code: RightsPending, HTTPStatus: 409, Retryable: true, Recovery: ActionRetry, Owner: "provenance", Summary: "限制尚未完成核验；按 retry_after_ms 再查，不默认放行"},
	{Code: SchemaInvalid, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "common", Summary: "请求或文档不符合 schema；按 details 逐条修正"},
	{Code: SelfReviewForbidden, HTTPStatus: 403, Retryable: false, Recovery: ActionNone, Owner: "ledger", Summary: "制作者不能审定或质检自己的产物"},
	{Code: SideEffectUnknown, HTTPStatus: 409, Retryable: false, Recovery: ActionReconcile, Owner: "agent_execution", Summary: "外部副作用结果不明；先对账，禁止换键重试"},
	{Code: StartKeyConflict, HTTPStatus: 409, Retryable: false, Recovery: ActionFixRequest, Owner: "agent_execution", Summary: "同一 execution_key 对应不同启动请求摘要"},
	{Code: StorageFull, HTTPStatus: 507, Retryable: false, Recovery: ActionHumanAction, Owner: "storage", Summary: "存储空间不足；需人释放空间，之后可用同一幂等键重试"},
	{Code: StorageUnavailable, HTTPStatus: 503, Retryable: true, Recovery: ActionRetry, Owner: "storage", Summary: "存储暂不可写或文件被占用；未确认的提交不会被报告成功"},
	{Code: TaskAlreadyClaimed, HTTPStatus: 409, Retryable: false, Recovery: ActionRefreshState, Owner: "tasks", Summary: "席位已被其他会话领取"},
	{Code: TokenExpired, HTTPStatus: 401, Retryable: false, Recovery: ActionReauthenticate, Owner: "identity", Summary: "会话或令牌已过期"},
	{Code: TokenRevoked, HTTPStatus: 401, Retryable: false, Recovery: ActionReauthenticate, Owner: "identity", Summary: "会话或令牌已吊销，或属于旧 auth_epoch/recovery_epoch"},
	{Code: TOTPReplay, HTTPStatus: 403, Retryable: false, Recovery: ActionHumanAction, Owner: "identity", Summary: "该动态码时间步已被使用；等待下一个验证码后重新输入"},
	{Code: TrashHeld, HTTPStatus: 409, Retryable: false, Recovery: ActionHumanAction, Owner: "ledger", Summary: "回收站条目处于暂停清除状态"},
	{Code: UnsupportedCapability, HTTPStatus: 422, Retryable: false, Recovery: ActionFixRequest, Owner: "agent_execution", Summary: "执行后端或宿主未声明任务要求的能力；不派发"},
	{Code: UseRestricted, HTTPStatus: 403, Retryable: false, Recovery: ActionNone, Owner: "provenance", Summary: "当前许可或来源限制禁止该用途"},
}

// superseded 列出旧草案中已被替代的错误码，服务端不得再返回。
var superseded = map[Code][]Code{
	"FORBIDDEN_ROLE":   {Forbidden},
	"LEASE_EXPIRED":    {LeaseStale},
	"MISSING_BLOBS":    {BlobGrantRequired},
	"POLICY_VIOLATION": {Forbidden, HumanProofRequired, UseRestricted},
	"UNAUTHENTICATED":  {AuthRequired, TokenExpired, TokenRevoked},
}
