// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"time"
)

// Defines values for OperationStatusStage.
const (
	OperationStatusStageBlocked     OperationStatusStage = "blocked"
	OperationStatusStageCancelled   OperationStatusStage = "cancelled"
	OperationStatusStageCommitted   OperationStatusStage = "committed"
	OperationStatusStageFailed      OperationStatusStage = "failed"
	OperationStatusStageInstalled   OperationStatusStage = "installed"
	OperationStatusStagePrepared    OperationStatusStage = "prepared"
	OperationStatusStageProjected   OperationStatusStage = "projected"
	OperationStatusStageQuarantined OperationStatusStage = "quarantined"
	OperationStatusStageReceiving   OperationStatusStage = "receiving"
)

// Valid indicates whether the value is a known member of the OperationStatusStage enum.
func (e OperationStatusStage) Valid() bool {
	switch e {
	case OperationStatusStageBlocked:
		return true
	case OperationStatusStageCancelled:
		return true
	case OperationStatusStageCommitted:
		return true
	case OperationStatusStageFailed:
		return true
	case OperationStatusStageInstalled:
		return true
	case OperationStatusStagePrepared:
		return true
	case OperationStatusStageProjected:
		return true
	case OperationStatusStageQuarantined:
		return true
	case OperationStatusStageReceiving:
		return true
	default:
		return false
	}
}

// Defines values for RecoveryAction.
const (
	RecoveryActionFixRequest     RecoveryAction = "fix_request"
	RecoveryActionHumanAction    RecoveryAction = "human_action"
	RecoveryActionNone           RecoveryAction = "none"
	RecoveryActionPollOperation  RecoveryAction = "poll_operation"
	RecoveryActionReauthenticate RecoveryAction = "reauthenticate"
	RecoveryActionReconcile      RecoveryAction = "reconcile"
	RecoveryActionRefreshState   RecoveryAction = "refresh_state"
	RecoveryActionResync         RecoveryAction = "resync"
	RecoveryActionRetry          RecoveryAction = "retry"
	RecoveryActionUploadContent  RecoveryAction = "upload_content"
)

// Valid indicates whether the value is a known member of the RecoveryAction enum.
func (e RecoveryAction) Valid() bool {
	switch e {
	case RecoveryActionFixRequest:
		return true
	case RecoveryActionHumanAction:
		return true
	case RecoveryActionNone:
		return true
	case RecoveryActionPollOperation:
		return true
	case RecoveryActionReauthenticate:
		return true
	case RecoveryActionReconcile:
		return true
	case RecoveryActionRefreshState:
		return true
	case RecoveryActionResync:
		return true
	case RecoveryActionRetry:
		return true
	case RecoveryActionUploadContent:
		return true
	default:
		return false
	}
}

// CommandType 命令类型，<module>.<command>，例如 ledger.commit_version。
type CommandType = string

// ErrorEnvelope 所有 HTTP、CLI JSON 与 adapter 协议共用的错误信封。code 必须在 error-codes.json 中登记，且 retryable、recovery_action 与登记一致。
type ErrorEnvelope struct {
	Error ErrorEnvelopeErrorBody `json:"error"`
}

// ErrorEnvelopeErrorBody defines model for ErrorEnvelopeErrorBody.
type ErrorEnvelopeErrorBody struct {
	// Code 稳定错误码，大写下划线；一经发布不改名。
	Code    string                      `json:"code"`
	Details *[]ErrorEnvelopeErrorDetail `json:"details,omitempty"`

	// Hint 修复提示。
	Hint *string `json:"hint,omitempty"`

	// Message 一句人话说明；不得包含凭据、签名 URL、无权来源的路径或哈希。
	Message string `json:"message"`

	// OperationId 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
	OperationId *Ulid `json:"operation_id,omitempty"`

	// RecoveryAction 调用方下一步的机器可读建议；枚举在 v1 内只增不改，客户端遇到未知值按 none 处理。
	RecoveryAction RecoveryAction `json:"recovery_action"`

	// Refs 调用者有权看到的相关引用（路径@版本、永久 URI 或对象 ID）。
	Refs *[]string `json:"refs,omitempty"`

	// RequestId 服务端请求编号，便于日志关联。
	RequestId *string `json:"request_id,omitempty"`

	// RetryAfterMs 建议的最短等待毫秒数；HTTP 同时返回 Retry-After。
	RetryAfterMs *int `json:"retry_after_ms,omitempty"`

	// Retryable 以同一幂等键原样重试是否可能成功。
	Retryable bool `json:"retryable"`
}

// ErrorEnvelopeErrorDetail 逐项细节，例如 schema 错误位置、租约失效原因、在用引用。
type ErrorEnvelopeErrorDetail struct {
	// Data 所属模块定义的附加结构化数据；不得包含敏感信息。
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`

	// Pointer RFC 6901 JSON Pointer。
	Pointer *JsonPointer `json:"pointer,omitempty"`

	// Reason 小写下划线的机器可读原因，例如 fence_mismatch、required。
	Reason string  `json:"reason"`
	Ref    *string `json:"ref,omitempty"`
}

// IdempotencyKey 客户端提供的幂等键；作用域为 (actor, project, command_type)。
type IdempotencyKey = string

// JsonPointer RFC 6901 JSON Pointer。
type JsonPointer = string

// LantaiUri 永久引用的外部 URI 形式。
type LantaiUri = string

// Module 服务端模块名，例如 identity、ledger、agent_execution；已知集合见 internal/contract/ownership。
type Module = string

// OperationStatus 持久操作的对外状态视图（GET /api/v1/operations/{operation_id}）。不返回令牌、签名 URL 或敏感堆栈；按当前读取权限过滤 result_refs。
type OperationStatus struct {
	// CommandType 命令类型，<module>.<command>，例如 ledger.commit_version。
	CommandType CommandType `json:"command_type"`

	// CreatedAt UTC 毫秒精度的 RFC 3339 时间，固定以 Z 结尾、3 位小数。
	CreatedAt Timestamp `json:"created_at"`

	// NextAction 调用方下一步的机器可读建议；枚举在 v1 内只增不改，客户端遇到未知值按 none 处理。
	NextAction RecoveryAction `json:"next_action"`

	// OperationId 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
	OperationId Ulid `json:"operation_id"`

	// OwnerModule 服务端模块名，例如 identity、ledger、agent_execution；已知集合见 internal/contract/ownership。
	OwnerModule Module `json:"owner_module"`

	// ParentOperationId 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
	ParentOperationId *Ulid `json:"parent_operation_id,omitempty"`

	// ProjectionPending 仅对 committed 有意义：该操作产生的事件是否仍未全部收录到 events.db。检索索引的落后量由查询水位另行报告。
	ProjectionPending *bool `json:"projection_pending,omitempty"`

	// Reason 终态或阻塞时的精简原因；code 在错误码注册表中登记。
	Reason *struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"reason,omitempty"`
	ResultRefs *[]OperationStatusResultRef `json:"result_refs,omitempty"`

	// Retryable 以原幂等键再次提交是否可能推进该操作。
	Retryable bool `json:"retryable"`

	// Stage receiving → prepared → installed → committed 为主线；projected 由 committed 且事件已全部收录推导；blocked/quarantined 保留字节待处置；failed/cancelled 为终态。
	Stage OperationStatusStage `json:"stage"`

	// UpdatedAt UTC 毫秒精度的 RFC 3339 时间，固定以 Z 结尾、3 位小数。
	UpdatedAt Timestamp `json:"updated_at"`
}

// OperationStatusAccepted HTTP 202 响应体：操作已持久接受但仍在进行中。
type OperationStatusAccepted struct {
	// OperationId 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
	OperationId Ulid `json:"operation_id"`

	// Stage receiving → prepared → installed → committed 为主线；projected 由 committed 且事件已全部收录推导；blocked/quarantined 保留字节待处置；failed/cancelled 为终态。
	Stage     OperationStatusStage `json:"stage"`
	StatusUrl string               `json:"status_url"`
}

// OperationStatusResultRef defines model for OperationStatusResultRef.
type OperationStatusResultRef struct {
	// Id 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
	Id Ulid `json:"id"`

	// Kind 对象类型，例如 asset、version、review、task_run。
	Kind string `json:"kind"`

	// Revision 服务端递增的修订号，从 1 开始；业务顺序以它为准，不以 ULID 时间推断。
	Revision *Revision `json:"revision,omitempty"`

	// Uri 永久引用的外部 URI 形式。
	Uri *LantaiUri `json:"uri,omitempty"`
}

// OperationStatusStage receiving → prepared → installed → committed 为主线；projected 由 committed 且事件已全部收录推导；blocked/quarantined 保留字节待处置；failed/cancelled 为终态。
type OperationStatusStage string

// RecoveryAction 调用方下一步的机器可读建议；枚举在 v1 内只增不改，客户端遇到未知值按 none 处理。
type RecoveryAction string

// Revision 服务端递增的修订号，从 1 开始；业务顺序以它为准，不以 ULID 时间推断。
type Revision = int

// Timestamp UTC 毫秒精度的 RFC 3339 时间，固定以 Z 结尾、3 位小数。
type Timestamp = time.Time

// Ulid 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
type Ulid = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// OperationID 服务端生成的 ULID，只接受 26 位大写 Crockford Base32 规范形式。
type OperationID = Ulid

// RequestID defines model for RequestID.
type RequestID = string

// Accepted HTTP 202 响应体：操作已持久接受但仍在进行中。
type Accepted = OperationStatusAccepted

// Error 所有 HTTP、CLI JSON 与 adapter 协议共用的错误信封。code 必须在 error-codes.json 中登记，且 retryable、recovery_action 与登记一致。
type Error = ErrorEnvelope

// GetOperationParams defines parameters for GetOperation.
type GetOperationParams struct {
	// XRequestId 客户端请求编号，仅用于日志关联，不参与请求摘要。
	XRequestId *RequestID `json:"X-Request-Id,omitempty"`
}
